name: sunmask
description: "Eine App zur Steuerung der SunMask Schlafmaske"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # <--- NEU
    sdk: flutter
  flutter_blue_plus: ^1.21.0
  permission_handler: ^11.0.1
  intl: ^0.19.1
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1  # NEU: Paket für die Logo-Änderung

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"  # Pfad zum App-Icon (empfohlen: 1024x1024 px)
  adaptive_icon_background: "#ffffff"  # Hintergrundfarbe für adaptive Icons (Android)
  adaptive_icon_foreground: "assets/icon_foreground.png"  # Optional für adaptive Icons

flutter:
  uses-material-design: true
