name: somnus
description: "Eine App zur Steuerung der SunMask Schlafmaske"
publish_to: 'none'

version: 1.0.0+2

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_blue_plus: ^1.21.0
  permission_handler: ^11.0.1
  geolocator: ^11.0.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  app_settings: ^5.1.1    # ✅ hinzugefügt für Bluetooth-Einstellungen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon_foreground.png"

flutter:
  uses-material-design: true
