# ios/Podfile
platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

install! 'cocoapods', :disable_input_output_paths => true

def flutter_installation
  flutter_application_path = File.expand_path('..')
  eval(File.read(File.join(flutter_application_path, '.flutter-plugins-dependencies')))
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_installation

  flutter_install_ios_pods File.dirname(File.realpath(__FILE__))
end
