name: Build iOS App

on:
  workflow_dispatch:
 

jobs:
  build_ios:
    name: Build iOS .ipa
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.31.0-0.1.pre'
          channel: 'beta'
          cache: true

      - name: Check Flutter & Dart Version
        run: flutter doctor -v

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install

      - name: Build iOS .ipa
        run: |
          flutter build ipa --release --export-options-plist=ios/Runner/ExportOptions.plist

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/ipa/*.ipa
