name: Build iOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.31.0-0.1.pre'
          channel: 'beta'
          cache: true

      - name: Check Flutter & Dart Version
        run: flutter doctor -v

      - name: Install CocoaPods
        run: sudo gem install cocoapods

      - name: Install dependencies
        run: flutter pub get

      - name: Generate App Icons
        run: flutter pub run flutter_launcher_icons:main

      - name: Run Flutter analyze
        run: flutter analyze

      - name: Build iOS app (debug)
        run: flutter build ios --debug
